In [3]:
from aocd import get_data
import numpy as np

In [8]:
data = get_data(day=9).splitlines()
data = np.array([list(data) for data in data]).astype(int)


array([[9, 8, 7, ..., 4, 2, 3],
       [9, 9, 6, ..., 9, 1, 0],
       [9, 8, 7, ..., 8, 9, 1],
       ...,
       [7, 9, 8, ..., 9, 5, 4],
       [8, 9, 9, ..., 9, 9, 5],
       [9, 2, 1, ..., 7, 8, 9]])

In [36]:
downwards = np.diff(data, axis=0)


In [39]:
data.shape

(100, 100)

In [48]:
empty = np.zeros(shape=data.shape)
for i in range(data.shape[0]):
    for j in range(data.shape[1]):
        try:
            if data[i-1][j] > data[i][j]:
                empty[i][j] += 1
        except:
            empty[i][j] += 0
        
        try:
            if data[i][j-1] > data[i][j]:
                empty[i][j] += 1
        except:
            empty[i][j] += 0

        try:
            if data[i+1][j] > data[i][j]:
                empty[i][j] += 1
        except:
            empty[i][j] += 0
        
        try:
            if data[i][j+1] > data[i][j]:
                empty[i][j] += 1
        except:
            empty[i][j] += 0





In [49]:
empty

array([[0., 2., 1., ..., 3., 3., 1.],
       [0., 0., 3., ..., 0., 3., 3.],
       [0., 3., 2., ..., 3., 0., 2.],
       ...,
       [2., 0., 3., ..., 0., 3., 2.],
       [2., 0., 0., ..., 0., 0., 2.],
       [0., 2., 3., ..., 2., 2., 0.]])

In [50]:
empty2 = int(empty/4)

TypeError: only size-1 arrays can be converted to Python scalars

In [44]:
if_pit = lambda pos: int(pos/4)

In [51]:
pit = np.vectorize(if_pit)(empty)

In [54]:
pit

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [58]:
sum(sum(pit*data)) + sum(sum(pit))

588